# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Scientific Computing
author: Charlie Dey and Scott J. Brandenberg
logo: logo.png
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Add a bibtex file so that we can create citations


launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
  
# Information about where the book exists on the web
repository:
  url: https://sjbrandenberg.github.io/training-scientific-computing/ # Online location of your book
  path_to_book: docs
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  google_analytics_id: G-XXXXXXXXXX

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: github
